[package]
name = "kg-syntax-test"
version = "0.1.0"
authors = ["jchlapinski <jakub.chlapinski@kodegenix.pl>"]
edition = "2018"
build = "build.rs"

[dependencies]
kg-diag = "0.4.0"
kg-display-derive = "0.1.1"

[build-dependencies]
kg-syntax-gen = { path = "../kg-syntax-gen" }
